### ISSUE TITLE
REL1_37 branch

### ISSUE THREAD

**Issue by Firefishy** [wikimedia/mediawiki-extensions-QuickInstantCommons#2]
@bawolff Please could you create a `REL1_37` branch? The current `master` chance seems to work OK.

If `REL1_37` branch is created it will activate the download for v1.37 on https://www.mediawiki.org/wiki/Special:ExtensionDistributor/QuickInstantCommons

**Comment by bawolff** [comment]
Done. Let me know if you run into any issues with the extension.

For future reference, the official bug tracker for this extension is https://phabricator.wikimedia.org. The github issues aren't really monitored.

**Comment by Firefishy** [comment]
:-( You branched from `REL1_38` which is out of date. `REL1_37` ideally should be updated to tip of `master`

**Comment by bawolff** [comment]
The only difference is a patch for support of a change that was in 1.39, but then got reverted from 1.39 so isn't really needed anyhow, along with a typo in a code comment.
